### ISSUE TITLE
What to do if two branches are different histories? 

### ISSUE THREAD

**Issue by phein** [monmouth-college-cs/sddc-reading-notes-monmouth-college-comp-335#37] opened 2019-09-19 21:34 UTC
I asked about this the other day but I forgot how to do it. 
Do I fetch from remote first and then branch from emptybranch?

**Comment by jlmayfield** [comment] 2019-09-19 21:44
If the problem is you can't do a merge because the history is different, then yes, fetch+merge or pull the remote branch into your local, then re-push that. You might still need to do some manual fixes. 

If your problem is it won't even let you attempt a PR because the histories have nothing in common, then you need to pull the base branch from the remote (probably emptybranch here), then add your files to that branch, commit, push, and initiate at PR.

**Comment by jlmayfield** [comment] 2019-09-19 21:46
[This StackOverflow Question](https://stackoverflow.com/questions/2364147/how-to-get-just-one-file-from-another-branch/2364223) discusses strategies for checking out single files from other branches.

**Comment by davidhsonic** [comment] 2019-09-19 22:45
@phein did you see #35?

**Comment by phein** [comment] 2019-09-19 23:40
@davidhsonic I was trying to push my branch which is Pyae-Chapter4 to Chapter4.
 ! [rejected]        Pyae-Chapter4 -> Chapter4 (non-fast-forward)
error: failed to push some refs to 'https://github.com/monmouth-college-cs/sddc-reading-notes-monmouth-college-comp-335.git'

**Comment by jlmayfield** [comment] 2019-09-20 01:54
I'm guessing you got this worked out @phein ? If so, go ahead and close the issue.

**Closed** 2019-09-20 16:03 UTC
